SET search_path = courses;


INSERT INTO course VALUES('787', 'C  Programming', 'Mech. Eng.', 4);
INSERT INTO course VALUES('238', 'The Music of Donovan', 'Mech. Eng.', 3);
INSERT INTO course VALUES('608', 'Electron Microscopy', 'Mech. Eng.', 3);
INSERT INTO course VALUES('539', 'International Finance', 'Comp. Sci.', 3);
INSERT INTO course VALUES('278', 'Greek Tragedy', 'Statistics', 4);
INSERT INTO course VALUES('972', 'Greek Tragedy', 'Psychology', 4);
INSERT INTO course VALUES('391', 'Virology', 'Biology', 3);
INSERT INTO course VALUES('814', 'Compiler Design', 'Elec. Eng.', 3);
INSERT INTO course VALUES('272', 'Geology', 'Mech. Eng.', 3);
INSERT INTO course VALUES('612', 'Mobile Computing', 'Physics', 3);
INSERT INTO course VALUES('237', 'Surfing', 'Cybernetics', 3);
INSERT INTO course VALUES('313', 'International Trade', 'Marketing', 3);
INSERT INTO course VALUES('887', 'Latin', 'Mech. Eng.', 3);
INSERT INTO course VALUES('328', 'Composition and Literature', 'Cybernetics', 3);
INSERT INTO course VALUES('984', 'Music of the 50s', 'History', 3);
INSERT INTO course VALUES('241', 'Biostatistics', 'Geology', 3);
INSERT INTO course VALUES('338', 'Graph Theory', 'Psychology', 3);
INSERT INTO course VALUES('400', 'Visual BASIC', 'Psychology', 4);
INSERT INTO course VALUES('760', 'How to Groom your Cat', 'Accounting', 3);
INSERT INTO course VALUES('629', 'Finite Element Analysis', 'Cybernetics', 3);
INSERT INTO course VALUES('762', 'The Monkeys', 'History', 4);
INSERT INTO course VALUES('242', 'Rock and Roll', 'Marketing', 3);
INSERT INTO course VALUES('482', 'FOCAL Programming', 'Psychology', 4);
INSERT INTO course VALUES('581', 'Calculus', 'Pol. Sci.', 4);
INSERT INTO course VALUES('843', 'Environmental Law', 'Math', 4);
INSERT INTO course VALUES('679', 'The Beatles', 'Math', 3);
INSERT INTO course VALUES('704', 'Marine Mammals', 'Geology', 4);
INSERT INTO course VALUES('774', 'Game Programming', 'Cybernetics', 4);
INSERT INTO course VALUES('591', 'Shakespeare', 'Pol. Sci.', 4);
INSERT INTO course VALUES('319', 'World History', 'Finance', 4);
INSERT INTO course VALUES('960', 'Tort Law', 'Civil Eng.', 3);
INSERT INTO course VALUES('274', 'Corporate Law', 'Comp. Sci.', 4);
INSERT INTO course VALUES('426', 'Video Gaming', 'Finance', 3);
INSERT INTO course VALUES('852', 'World History', 'Athletics', 4);
INSERT INTO course VALUES('408', 'Bankruptcy', 'Accounting', 3);
INSERT INTO course VALUES('808', 'Organic Chemistry', 'English', 4);
INSERT INTO course VALUES('902', 'Existentialism', 'Finance', 3);
INSERT INTO course VALUES('730', 'Quantum Mechanics', 'Elec. Eng.', 4);
INSERT INTO course VALUES('362', 'Embedded Systems', 'Finance', 4);
INSERT INTO course VALUES('341', 'Quantum Mechanics', 'Cybernetics', 3);
INSERT INTO course VALUES('582', 'Marine Mammals', 'Cybernetics', 3);
INSERT INTO course VALUES('867', 'The IBM 360 Architecture', 'History', 3);
INSERT INTO course VALUES('169', 'Marine Mammals', 'Elec. Eng.', 3);
INSERT INTO course VALUES('680', 'Electricity and Magnetism', 'Civil Eng.', 3);
INSERT INTO course VALUES('227', 'Elastic Structures', 'Languages', 4);
INSERT INTO course VALUES('991', 'Transaction Processing', 'Psychology', 3);
INSERT INTO course VALUES('366', 'Computational Biology', 'English', 3);
INSERT INTO course VALUES('376', 'Cost Accounting', 'Physics', 4);
INSERT INTO course VALUES('489', 'Journalism', 'Astronomy', 4);
INSERT INTO course VALUES('663', 'Geology', 'Psychology', 3);
INSERT INTO course VALUES('461', 'Physical Chemistry', 'Math', 3);
INSERT INTO course VALUES('105', 'Image Processing', 'Astronomy', 3);
INSERT INTO course VALUES('407', 'Industrial Organization', 'Languages', 4);
INSERT INTO course VALUES('254', 'Security', 'Cybernetics', 3);
INSERT INTO course VALUES('998', 'Immunology', 'Civil Eng.', 4);
INSERT INTO course VALUES('457', 'Systems Software', 'History', 3);
INSERT INTO course VALUES('401', 'Sanitary Engineering', 'Athletics', 4);
INSERT INTO course VALUES('127', 'Thermodynamics', 'Geology', 3);
INSERT INTO course VALUES('399', 'RPG Programming', 'Pol. Sci.', 4);
INSERT INTO course VALUES('949', 'Japanese', 'Comp. Sci.', 3);
INSERT INTO course VALUES('496', 'Aquatic Chemistry', 'Cybernetics', 3);
INSERT INTO course VALUES('334', 'International Trade', 'Athletics', 3);
INSERT INTO course VALUES('544', 'Differential Geometry', 'Statistics', 3);
INSERT INTO course VALUES('451', 'Database System Concepts', 'Pol. Sci.', 4);
INSERT INTO course VALUES('190', 'Romantic Literature', 'Civil Eng.', 3);
INSERT INTO course VALUES('630', 'Religion', 'English', 3);
INSERT INTO course VALUES('761', 'Existentialism', 'Athletics', 3);
INSERT INTO course VALUES('804', 'Introduction to Burglary', 'Cybernetics', 4);
INSERT INTO course VALUES('781', 'Compiler Design', 'Finance', 4);
INSERT INTO course VALUES('805', 'Composition and Literature', 'Statistics', 4);
INSERT INTO course VALUES('318', 'Geology', 'Cybernetics', 3);
INSERT INTO course VALUES('353', 'Operating Systems', 'Psychology', 3);
INSERT INTO course VALUES('394', 'C  Programming', 'Athletics', 3);
INSERT INTO course VALUES('137', 'Manufacturing', 'Finance', 3);
INSERT INTO course VALUES('192', 'Drama', 'Languages', 4);
INSERT INTO course VALUES('681', 'Medieval Civilization or Lack Thereof', 'English', 3);
INSERT INTO course VALUES('377', 'Differential Geometry', 'Astronomy', 4);
INSERT INTO course VALUES('959', 'Bacteriology', 'Physics', 4);
INSERT INTO course VALUES('235', 'International Trade', 'Math', 3);
INSERT INTO course VALUES('421', 'Aquatic Chemistry', 'Athletics', 4);
INSERT INTO course VALUES('647', 'Service-Oriented Architectures', 'Comp. Sci.', 4);
INSERT INTO course VALUES('598', 'Number Theory', 'Accounting', 4);
INSERT INTO course VALUES('858', 'Sailing', 'Math', 4);
INSERT INTO course VALUES('487', 'Physical Chemistry', 'History', 3);
INSERT INTO course VALUES('133', 'Antidisestablishmentarianism in Modern America', 'Biology', 4);
INSERT INTO course VALUES('267', 'Hydraulics', 'Physics', 4);
INSERT INTO course VALUES('200', 'The Music of the Ramones', 'Accounting', 4);
INSERT INTO course VALUES('664', 'Elastic Structures', 'English', 3);
INSERT INTO course VALUES('599', 'Mechanics', 'Psychology', 4);
INSERT INTO course VALUES('456', 'Hebrew', 'Civil Eng.', 3);
INSERT INTO course VALUES('558', 'Environmental Law', 'Psychology', 3);
INSERT INTO course VALUES('919', 'Computability Theory', 'Math', 3);
INSERT INTO course VALUES('546', 'Creative Writing', 'Mech. Eng.', 4);
INSERT INTO course VALUES('969', 'The Monkeys', 'Astronomy', 4);
INSERT INTO course VALUES('877', 'Composition and Literature', 'Biology', 4);
INSERT INTO course VALUES('337', 'Differential Geometry', 'Statistics', 3);
INSERT INTO course VALUES('983', 'Virology', 'Languages', 4);
INSERT INTO course VALUES('603', 'Care and Feeding of Cats', 'Statistics', 3);
INSERT INTO course VALUES('747', 'International Practicum', 'Comp. Sci.', 4);
INSERT INTO course VALUES('659', 'Geology', 'Math', 4);
INSERT INTO course VALUES('559', 'Martian History', 'Biology', 3);
INSERT INTO course VALUES('403', 'Immunology', 'Biology', 3);
INSERT INTO course VALUES('436', 'Stream Processing', 'Physics', 4);
INSERT INTO course VALUES('656', 'Groups and Rings', 'Civil Eng.', 4);
INSERT INTO course VALUES('731', 'The Music of Donovan', 'Physics', 4);
INSERT INTO course VALUES('820', 'Assembly Language Programming', 'Cybernetics', 3);
INSERT INTO course VALUES('898', 'Petroleum Engineering', 'Marketing', 4);
INSERT INTO course VALUES('545', 'International Practicum', 'History', 3);
INSERT INTO course VALUES('893', 'Systems Software', 'Cybernetics', 3);
INSERT INTO course VALUES('818', 'Environmental Law', 'Astronomy', 4);
INSERT INTO course VALUES('618', 'Thermodynamics', 'English', 4);
INSERT INTO course VALUES('416', 'Data Mining', 'Accounting', 3);
INSERT INTO course VALUES('716', 'Medieval Civilization or Lack Thereof', 'Languages', 4);
INSERT INTO course VALUES('130', 'Differential Geometry', 'Physics', 3);
INSERT INTO course VALUES('476', 'International Communication', 'Astronomy', 4);
INSERT INTO course VALUES('101', 'Diffusion and Phase Transformation', 'Mech. Eng.', 3);
INSERT INTO course VALUES('123', 'Differential Equations', 'Mech. Eng.', 3);
INSERT INTO course VALUES('209', 'International Trade', 'Cybernetics', 4);
INSERT INTO course VALUES('352', 'Compiler Design', 'Psychology', 4);
INSERT INTO course VALUES('393', 'Aerodynamics', 'Languages', 3);
INSERT INTO course VALUES('795', 'Death and Taxes', 'Marketing', 3);
INSERT INTO course VALUES('577', 'The Music of Dave Edmunds', 'Elec. Eng.', 3);
INSERT INTO course VALUES('584', 'Computability Theory', 'Comp. Sci.', 3);
INSERT INTO course VALUES('864', 'Heat Transfer', 'Geology', 3);
INSERT INTO course VALUES('594', 'Cognitive Psychology', 'Finance', 3);
INSERT INTO course VALUES('802', 'African History', 'Cybernetics', 3);
INSERT INTO course VALUES('692', 'Cat Herding', 'Athletics', 3);
INSERT INTO course VALUES('258', 'Colloid and Surface Chemistry', 'Math', 3);
INSERT INTO course VALUES('748', 'Tort Law', 'Cybernetics', 4);
INSERT INTO course VALUES('770', 'European History', 'Pol. Sci.', 3);
INSERT INTO course VALUES('340', 'Corporate Law', 'History', 3);
INSERT INTO course VALUES('158', 'Elastic Structures', 'Cybernetics', 3);
INSERT INTO course VALUES('276', 'Game Design', 'Comp. Sci.', 4);
INSERT INTO course VALUES('626', 'Multimedia Design', 'History', 4);
INSERT INTO course VALUES('696', 'Heat Transfer', 'Marketing', 4);
INSERT INTO course VALUES('239', 'The Music of the Ramones', 'Physics', 4);
INSERT INTO course VALUES('962', 'Animal Behavior', 'Psychology', 3);
INSERT INTO course VALUES('527', 'Graphics', 'Finance', 3);
INSERT INTO course VALUES('275', 'Romantic Literature', 'Languages', 3);
INSERT INTO course VALUES('549', 'Banking and Finance', 'Astronomy', 3);
INSERT INTO course VALUES('974', 'Astronautics', 'Accounting', 3);
INSERT INTO course VALUES('897', 'How to Succeed in Business Without Really Trying', 'Languages', 4);
INSERT INTO course VALUES('359', 'Game Programming', 'Comp. Sci.', 4);
INSERT INTO course VALUES('345', 'Race Car Driving', 'Accounting', 4);
INSERT INTO course VALUES('371', 'Milton', 'Finance', 3);
INSERT INTO course VALUES('284', 'Topology', 'Comp. Sci.', 4);
INSERT INTO course VALUES('642', 'Video Gaming', 'Psychology', 3);
INSERT INTO course VALUES('769', 'Logic', 'Elec. Eng.', 4);
INSERT INTO course VALUES('947', 'Real-Time Database Systems', 'Accounting', 3);
INSERT INTO course VALUES('265', 'Thermal Physics', 'Cybernetics', 4);
INSERT INTO course VALUES('927', 'Differential Geometry', 'Cybernetics', 4);
INSERT INTO course VALUES('694', 'Optics', 'Math', 3);
INSERT INTO course VALUES('580', 'The Music of Dave Edmunds', 'Physics', 4);
INSERT INTO course VALUES('324', 'Ponzi Schemes', 'Civil Eng.', 3);
INSERT INTO course VALUES('349', 'Networking', 'Finance', 4);
INSERT INTO course VALUES('392', 'Recursive Function Theory', 'Astronomy', 4);
INSERT INTO course VALUES('735', 'Greek Tragedy', 'Geology', 3);
INSERT INTO course VALUES('702', 'Arabic', 'Biology', 3);
INSERT INTO course VALUES('458', 'The Renaissance', 'Civil Eng.', 4);
INSERT INTO course VALUES('348', 'Compiler Design', 'Elec. Eng.', 3);
INSERT INTO course VALUES('500', 'Networking', 'Astronomy', 3);
INSERT INTO course VALUES('494', 'Automobile Mechanics', 'Pol. Sci.', 4);
INSERT INTO course VALUES('411', 'Music of the 80s', 'Mech. Eng.', 4);
INSERT INTO course VALUES('493', 'Music of the 50s', 'Geology', 3);
INSERT INTO course VALUES('396', 'C  Programming', 'Languages', 3);
INSERT INTO course VALUES('810', 'Mobile Computing', 'Geology', 3);
INSERT INTO course VALUES('631', 'Plasma Physics', 'Elec. Eng.', 4);
INSERT INTO course VALUES('486', 'Accounting', 'Geology', 3);
INSERT INTO course VALUES('963', 'Groups and Rings', 'Languages', 4);
INSERT INTO course VALUES('445', 'Biostatistics', 'Finance', 3);
INSERT INTO course VALUES('292', 'Electron Microscopy', 'English', 4);
INSERT INTO course VALUES('830', 'Sensor Networks', 'Astronomy', 4);
INSERT INTO course VALUES('604', 'UNIX System Programmming', 'Statistics', 4);
INSERT INTO course VALUES('857', 'UNIX System Programmming', 'Geology', 4);
INSERT INTO course VALUES('304', 'Music 2 New for your Instructor', 'Finance', 4);
INSERT INTO course VALUES('922', 'Microeconomics', 'Finance', 4);
INSERT INTO course VALUES('571', 'Plastics', 'Comp. Sci.', 4);
INSERT INTO course VALUES('628', 'Existentialism', 'Accounting', 3);
INSERT INTO course VALUES('841', 'Fractal Geometry', 'Mech. Eng.', 4);
INSERT INTO course VALUES('586', 'Image Processing', 'Finance', 4);
INSERT INTO course VALUES('139', 'Number Theory', 'English', 4);
INSERT INTO course VALUES('666', 'Multivariable Calculus', 'Accounting', 3);
INSERT INTO course VALUES('443', 'Journalism', 'Physics', 4);
INSERT INTO course VALUES('195', 'Numerical Methods', 'Geology', 4);
INSERT INTO course VALUES('634', 'Astronomy', 'Cybernetics', 4);
INSERT INTO course VALUES('224', 'International Finance', 'Athletics', 3);
INSERT INTO course VALUES('791', 'Operating Systems', 'Marketing', 3);
INSERT INTO course VALUES('875', 'Bioinformatics', 'Cybernetics', 3);
INSERT INTO course VALUES('958', 'Fiction Writing', 'Mech. Eng.', 3);
INSERT INTO course VALUES('415', 'Numerical Methods', 'Biology', 3);
INSERT INTO course VALUES('442', 'Strength of Materials', 'Athletics', 3);
INSERT INTO course VALUES('468', 'Fractal Geometry', 'Civil Eng.', 4);
INSERT INTO course VALUES('270', 'Music of the 90s', 'Math', 4);
INSERT INTO course VALUES('966', 'Sanitary Engineering', 'History', 3);
INSERT INTO course VALUES('793', 'Decison Support Systems', 'Civil Eng.', 3);
INSERT INTO course VALUES('236', 'Design and Analysis of Algorithms', 'Mech. Eng.', 3);
INSERT INTO course VALUES('792', 'Image Processing', 'Accounting', 3);
INSERT INTO course VALUES('561', 'The Music of Donovan', 'Elec. Eng.', 4);
INSERT INTO course VALUES('344', 'Quantum Mechanics', 'Accounting', 4);
INSERT INTO course VALUES('780', 'Geology', 'Psychology', 3);