SET search_path = courses;


INSERT INTO classroom VALUES('Lamberton', 134, 10);
INSERT INTO classroom VALUES('Chandler', 375, 10);
INSERT INTO classroom VALUES('Fairchild', 145, 27);
INSERT INTO classroom VALUES('Nassau', 45, 92);
INSERT INTO classroom VALUES('Grace', 40, 34);
INSERT INTO classroom VALUES('Whitman', 134, 120);
INSERT INTO classroom VALUES('Lamberton', 143, 10);
INSERT INTO classroom VALUES('Taylor', 812, 115);
INSERT INTO classroom VALUES('Saucon', 113, 109);
INSERT INTO classroom VALUES('Painter', 86, 97);
INSERT INTO classroom VALUES('Alumni', 547, 26);
INSERT INTO classroom VALUES('Alumni', 143, 47);
INSERT INTO classroom VALUES('Drown', 757, 18);
INSERT INTO classroom VALUES('Saucon', 180, 15);
INSERT INTO classroom VALUES('Whitman', 434, 32);
INSERT INTO classroom VALUES('Saucon', 844, 24);
INSERT INTO classroom VALUES('Bronfman', 700, 12);
INSERT INTO classroom VALUES('Polya', 808, 28);
INSERT INTO classroom VALUES('Gates', 707, 65);
INSERT INTO classroom VALUES('Gates', 314, 10);
INSERT INTO classroom VALUES('Main', 45, 30);
INSERT INTO classroom VALUES('Taylor', 183, 71);
INSERT INTO classroom VALUES('Power', 972, 10);
INSERT INTO classroom VALUES('Garfield', 119, 59);
INSERT INTO classroom VALUES('Rathbone', 261, 60);
INSERT INTO classroom VALUES('Stabler', 105, 113);
INSERT INTO classroom VALUES('Power', 717, 12);
INSERT INTO classroom VALUES('Main', 425, 22);
INSERT INTO classroom VALUES('Lambeau', 348, 51);
INSERT INTO classroom VALUES('Chandler', 804, 11);